### ISSUE TITLE
When I try to use this directive I get error

### ISSUE THREAD

**Issue by andrewt3000** [rootux/angular-highcharts-directive#10]
When I try to use this directive I get error

Highcharts error #13: www.highcharts.com/errors/13 

This error occurs if the chart.renderTo option is misconfugured so that Highcharts is unable to find the HTML element to render the chart in.

**Comment by nichochar** [comment]
I'm closing this, as it seems to not have had a lot of activity, and seems to be a simple missing HTML bug
