### ISSUE TITLE
Version #0.4.0

### ISSUE THREAD

**Issue by uberspeck** [rootux/angular-highcharts-directive#17]
FYI, i noticed there isn't a tag corresponding to the current version of the lib. If you just run the following commands people will be able to specify the version they want...

```
$ git tag v0.4.0
$ git push origin v0.4.0
```

**Comment by AVVS** [comment]
bump

**Comment by nichochar** [comment]
done, thanks

**Comment by nichochar** [comment]
https://github.com/rootux/angular-highcharts-directive/releases/tag/v0.4.0
