### ISSUE TITLE
chart is undefined inside the watch

### ISSUE THREAD

**Issue by robert-irribarren** [rootux/angular-highcharts-directive#21]
i had to change a line in your directive to get it work using your data for compatibility i reccomend you merge these. Sorry, for not making a commit myself

    return {
        restrict: 'ACE',
        template: '<div></div>',
        scope: {
            chartData: "=value",
            chartObj: "=?"
        },
        transclude: true,
        replace: true,
        link: function($scope, $element, $attrs) {

            //Update when charts data changes
            $scope.$watch('chartData', function(value) {
                if (!value)
                    return;
                if (!$scope.chartData.chart) <--- THIS LINE
                	$scope.chartData.chart = {}; <--- ALSO THIS
                // use default values if nothing is specified in the given settings
                $scope.chartData.chart.renderTo = $scope.chartData.chart.renderTo || $element[0];
                if ($attrs.type)
                    $scope.chartData.chart.type = $scope.chartData.chart.type || $attrs.type;
                if ($attrs.height)
                    $scope.chartData.chart.height = $scope.chartData.chart.height || $attrs.height;
                if ($attrs.width)
                    $scope.chartData.chart.width = $scope.chartData.chart.type || $attrs.width;

                $scope.chartObj = new Highcharts.Chart($scope.chartData);
            });
        }
    };

**Comment by nichochar** [comment]
To be a little more elegant, those 2 new lines can be merged into one (but thanks for the suggested fix):
                    $scope.chartData.chart = $scope.chartData.chart || {};
